<?php
global $vc_add_css_animation;

add_filter('vc_iconpicker-type-fontawesome', 'vc_iconpicker_type_fontawesome');
vc_map(array(
  "name" => esc_html__("Text block with an Icon", 'ajzaa'),
  "base" => "ajzaa_text_icon",
  "icon" => get_template_directory_uri() . "/images/icon/meknes.png",
  "content_element" => true,
  "is_container" => FALSE,
  "category" => 'Webdevia Shortcodes',
  "params" => array(
    array(
      "heading" => esc_html__("Alignment", 'ajzaa'),
      "type" => "dropdown",
      "param_name" => "box_alignment",
      'value' => array('Left (Default)' => 'left',
        'center' => 'center',
        'right' => 'right',
      ),
    ),
    array(
      "heading" => esc_html__("Show subtitle", 'ajzaa'),
      "type" => "dropdown",
      "param_name" => "box_show_subtitle",
      'value' => array(
        'none' => 'none',
        'Show SubTitle' => 'ajzaa_show',
      ),
    ),
    array(
      "heading" => esc_html__("Switch Title and Subtitle", 'ajzaa'),
      "type" => "dropdown",
      "param_name" => "ajzaa_switch_title_subtitle",
      'value' => array(
        'Title / Subtitle' => 'true',
        'Subtitle / Title' => 'false',
      ),
      "dependency" => Array("element" => "box_show_subtitle", "value" => array('ajzaa_show')),
    ),
    array(
      "heading" => esc_html__("Icon Position", 'ajzaa'),
      "type" => "dropdown",
      "param_name" => "box_style",
      'value' => array('(Default)' => 'style1',
        'Icon Left' => 'style2',
        'Icon right' => 'style3',
      ),
    ),
    array(
      "heading" => esc_html__("Content/Title Box Padding", 'ajzaa'),
      "type" => "textfield",
      "param_name" => "box_contenttitle_padding",
      "value" => '0px',
    ),
    array(
      "heading" => esc_html__("Hover Effect", 'ajzaa'),
      "type" => "dropdown",
      "param_name" => "box_hover_style",
      'value' => array('None' => 'none',
        'Hover Style I' => 'hover_style1',
        'Hover Style II' => 'hover_style2',
        'Hover Style III' => 'hover_style3',
      ),
    ),
    array(
      "heading" => esc_html__("Apply Link To", 'ajzaa'),
      "type" => "dropdown",
      "param_name" => "box_link_apply",
      'value' => array('No Link (Default)' => 'no_link',
        'All Box' => 'all_box',
        'Title Box' => 'title_box',
        'Read More button' => 'read_more_btn',
      ),
    ),
    array(
      "heading" => esc_html__("Box Background", 'ajzaa'),
      "type" => "dropdown",
      "param_name" => "box_background",
      'value' => array('None' => 'none',
        'Background Color' => 'box_background_type_color',
        'Background Image' => 'box_background_type_image',
      ),
    ),
    array(
      "heading" => esc_html__("Box background Color", 'ajzaa'),
      "type" => "colorpicker",
      "param_name" => "box_background_color",
      "value" => '',
      "dependency" => Array("element" => "box_background", "value" => array('box_background_type_color')),
    ),
    array(
      "heading" => esc_html__("Box Hover Background Color", 'ajzaa'),
      "type" => "colorpicker",
      "param_name" => "box_hover_background_color",
      "value" => '',
      "dependency" => Array("element" => "box_background", "value" => array('box_background_type_color')),
    ),
    array(
      "heading" => esc_html__("Box background Image", 'ajzaa'),
      "type" => "attach_image",
      "param_name" => "box_background_image",
      "value" => '',
      "dependency" => Array("element" => "box_background", "value" => array('box_background_type_image')),
    ),
    array(
      "heading" => esc_html__("Extra class name", 'ajzaa'),
      "type" => "textfield",
      "param_name" => "box_extra_class_name",
      "value" => '',
      "description" => 'If you wish to style particular content element differently, then use this field to add a class name and then refer to it in your css file.'
    ),

    //__________________Title_______________________
    array(
      "heading" => esc_html__("Title Text", 'ajzaa'),
      "type" => "textfield",
      "param_name" => "box_title",
      "value" => 'I am a Title change my',
      "group" => "Title",
    ),
    array(
      "heading" => esc_html__("Title Balises", 'ajzaa'),
      "type" => "dropdown",
      "param_name" => "box_title_balises",
      "value" => 'h2',
      'value' => array(
        esc_html__('h2 (Default)', 'ajzaa') => 'h2',
        'h3' => 'h3',
        'h4' => 'h4',
        'h5' => 'h5',
        'h6' => 'h6',
        'div' => 'div',
      ),
      "group" => "Title",
    ),
    array(
      "heading" => esc_html__("Title Text Padding", 'ajzaa'),
      "type" => "textfield",
      "param_name" => "box_title_padding",
      "value" => '0px',
      "group" => "Title",
    ),
    array(
      "heading" => esc_html__("Text Color", 'ajzaa'),
      "type" => "colorpicker",
      "param_name" => "box_title_color",
      "value" => '#eee',
      "group" => "Title",
    ),
    array(
      "heading" => esc_html__("Title Separator Color", 'ajzaa'),
      "type" => "colorpicker",
      "param_name" => "box_title_separator_color",
      "value" => '',
      "group" => "Title",
    ),
    array(
      "heading" => esc_html__("Title Separator Height", 'ajzaa'),
      "type" => "textfield",
      "param_name" => "box_title_separator_height",
      "value" => '',
      "group" => "Title",
    ),
    array(
      "heading" => esc_html__("Title Separator Width", 'ajzaa'),
      "type" => "textfield",
      "param_name" => "box_title_separator_width",
      "value" => '',
      "group" => "Title",
    ),
    //////////// Typography Title
    array(
      "type" => "textfield",
      "heading" => esc_html__("Font Family", 'ajzaa'),
      "param_name" => "ajzaa_title_font_family",
      "group" => "Title",
    ),

    array(
      "type" => "dropdown",
      "heading" => esc_html__("Font Weight", 'ajzaa'),
      "param_name" => "ajzaa_title_font_weight",
      'value' => array(
        esc_html__('Default', 'ajzaa') => '400',
        '100' => '100',
        '200' => '200',
        '300' => '300',
        '500' => '500',
        '600' => '600',
        '700' => '700',
        '800' => '800',
        '900' => '900',
      ),
      "group" => "Title"
    ),
    array(
      "type" => "textfield",
      "class" => "",
      "heading" => esc_html__("Font Size", 'ajzaa'),
      "param_name" => "ajzaa_title_font_size",
      "min" => 14,
      "suffix" => "px",
      "group" => "Title",
    ),

    array(
      "type" => "dropdown",
      "heading" => esc_html__("Text Transform", 'ajzaa'),
      "param_name" => "ajzaa_title_text_transform",
      'value' => array(
        esc_html__('Default', 'ajzaa') => 'None',
        'lowercase' => 'Lowercase',
        'uppercase' => 'Uppercase',
        'capitalize' => 'Capitalize',
        'inherit' => 'Inherit',
      ),
      "group" => "Title"
    ),
    array(
      "type" => "textfield",
      "class" => "",
      "heading" => esc_html__("Line Height", 'ajzaa'),
      "param_name" => "ajzaa_title_line_height",
      "value" => "",
      "suffix" => "px",
      "group" => "Title"
    ),
    array(
      "type" => "textfield",
      "class" => "",
      "heading" => esc_html__("Letter spacing", 'ajzaa'),
      "param_name" => "ajzaa_title_letter_spacing",
      "value" => "",
      "suffix" => "px",
      "group" => "Title"
    ),
    //__________________SubTitle_______________________
    array(
      "heading" => esc_html__("Subtitle Text", 'ajzaa'),
      "type" => "textfield",
      "param_name" => "box_subtitle",
      "value" => 'I am a Subtitle change my',
      "group" => "Subtitle",
      "dependency" => Array("element" => "box_show_subtitle", "value" => array('ajzaa_show')),
    ),
    array(
      "heading" => esc_html__("Title SubText Padding", 'ajzaa'),
      "type" => "textfield",
      "param_name" => "box_subtitle_padding",
      "value" => '0px',
      "group" => "Subtitle",
      "dependency" => Array("element" => "box_show_subtitle", "value" => array('ajzaa_show')),
    ),
    array(
      "heading" => esc_html__("SubTitle Text Color", 'ajzaa'),
      "type" => "colorpicker",
      "param_name" => "box_subtitle_color",
      "value" => '#eee',
      "group" => "Subtitle",
      "dependency" => Array("element" => "box_show_subtitle", "value" => array('ajzaa_show')),
    ),
    //////////// Typography SubTitle
    array(
      "type" => "textfield",
      "heading" => esc_html__("Font Family", 'ajzaa'),
      "param_name" => "ajzaa_subtitle_font_family",
      "group" => "Subtitle",
      "dependency" => Array("element" => "box_show_subtitle", "value" => array('ajzaa_show')),
    ),

    array(
      "type" => "dropdown",
      "heading" => esc_html__("Font Weight", 'ajzaa'),
      "param_name" => "ajzaa_subtitle_font_weight",
      'value' => array(
        esc_html__('Default', 'ajzaa') => '400',
        '100' => '100',
        '200' => '200',
        '300' => '300',
        '500' => '500',
        '600' => '600',
        '700' => '700',
        '800' => '800',
        '900' => '900',
      ),
      "group" => "Subtitle",
      "dependency" => Array("element" => "box_show_subtitle", "value" => array('ajzaa_show')),
    ),
    array(
      "type" => "textfield",
      "class" => "",
      "heading" => esc_html__("Font Size", 'ajzaa'),
      "param_name" => "ajzaa_subtitle_font_size",
      "min" => 14,
      "suffix" => "px",
      "group" => "Subtitle",
      "dependency" => Array("element" => "box_show_subtitle", "value" => array('ajzaa_show')),
    ),

    array(
      "type" => "dropdown",
      "heading" => esc_html__("Text Transform", 'ajzaa'),
      "param_name" => "ajzaa_subtitle_text_transform",
      'value' => array(
        esc_html__('Default', 'ajzaa') => 'None',
        'lowercase' => 'Lowercase',
        'uppercase' => 'Uppercase',
        'capitalize' => 'Capitalize',
        'inherit' => 'Inherit',
      ),
      "group" => "Subtitle",
      "dependency" => Array("element" => "box_show_subtitle", "value" => array('ajzaa_show')),
    ),
    array(
      "type" => "textfield",
      "class" => "",
      "heading" => esc_html__("Line Height", 'ajzaa'),
      "param_name" => "ajzaa_subtitle_line_height",
      "value" => "",
      "suffix" => "px",
      "group" => "Subtitle",
      "dependency" => Array("element" => "box_show_subtitle", "value" => array('ajzaa_show')),
    ),
    array(
      "type" => "textfield",
      "class" => "",
      "heading" => esc_html__("Letter spacing", 'ajzaa'),
      "param_name" => "ajzaa_subtitle_letter_spacing",
      "value" => "",
      "suffix" => "px",
      "group" => "Subtitle",
      "dependency" => Array("element" => "box_show_subtitle", "value" => array('ajzaa_show')),
    ),
    //__________________Content_______________________
    array(
      "type" => "textarea",
      "heading" => esc_html__("Content Text", 'ajzaa'),
      "param_name" => "box_content",
      "value" => "",
      "group" => "Content",
    ),
    array(
      "heading" => esc_html__("Content Text Padding", 'ajzaa'),
      "type" => "textfield",
      "param_name" => "box_content_padding",
      "value" => '0px',
      "group" => "Content",
    ),
    array(
      "heading" => esc_html__("Content Text Color", 'ajzaa'),
      "type" => "colorpicker",
      "param_name" => "box_content_color",
      "value" => '#eee',
      "group" => "Content",
    ),
    //////////// Typography SubTitle
    array(
      "type" => "textfield",
      "heading" => esc_html__("Font Family", 'ajzaa'),
      "param_name" => "ajzaa_content_font_family",
      "group" => "Content",
    ),
    array(
      "type" => "dropdown",
      "heading" => esc_html__("Font Weight", 'ajzaa'),
      "param_name" => "ajzaa_content_font_weight",
      'value' => array(
        esc_html__('Default', 'ajzaa') => '400',
        '100' => '100',
        '200' => '200',
        '300' => '300',
        '500' => '500',
        '600' => '600',
        '700' => '700',
        '800' => '800',
        '900' => '900',
      ),
      "group" => "Content"
    ),
    array(
      "type" => "textfield",
      "class" => "",
      "heading" => esc_html__("Font Size", 'ajzaa'),
      "param_name" => "ajzaa_content_font_size",
      "min" => 14,
      "suffix" => "px",
      "group" => "Content",
    ),

    array(
      "type" => "dropdown",
      "heading" => esc_html__("Text Transform", 'ajzaa'),
      "param_name" => "ajzaa_content_text_transform",
      'value' => array(
        esc_html__('Default', 'ajzaa') => 'None',
        'lowercase' => 'Lowercase',
        'uppercase' => 'Uppercase',
        'capitalize' => 'Capitalize',
        'inherit' => 'Inherit',
      ),
      "group" => "Content"
    ),
    array(
      "type" => "textfield",
      "class" => "",
      "heading" => esc_html__("Line Height", 'ajzaa'),
      "param_name" => "ajzaa_content_line_height",
      "value" => "",
      "suffix" => "px",
      "group" => "Content"
    ),
    array(
      "type" => "textfield",
      "class" => "",
      "heading" => esc_html__("Letter spacing", 'ajzaa'),
      "param_name" => "ajzaa_content_letter_spacing",
      "value" => "",
      "suffix" => "px",
      "group" => "Content"
    ),
    //__________________Icon_______________________
    array(
      'type' => 'dropdown',
      'heading' => esc_html__('Icon', 'ajzaa'),
      'param_name' => 'ajzaa_switch',
      'value' => array(
        esc_html__('None', 'ajzaa') => 'None',
        'Icon' => 'ajzaa_icon',
        'Image' => 'ajzaa_image',
      ),
      "group" => "Icon",
    ),
    array(
      'type' => 'attach_image',
      'heading' => esc_html__('Image', 'ajzaa'),
      'param_name' => 'ajzaa_source_image',
      "group" => "Icon",
      "dependency" => Array("element" => "ajzaa_switch", "value" => array('ajzaa_image')),
    ),
    array(
      "type" => "textfield",
      "class" => "",
      "heading" => esc_html__("Image Size", 'ajzaa'),
      "param_name" => "ajzaa_size_image",
      "value" => "",
      "suffix" => "px",
      "group" => "Icon",
      "dependency" => Array("element" => "ajzaa_switch", "value" => array('ajzaa_image')),
    ),
    array(
      'type' => 'iconpicker',
      'heading' => esc_html__('Icon', 'ajzaa'),
      'param_name' => 'ajzaa_icon_fontawesome',
      'settings' => array(
        'emptyIcon' => true, // default true, display an "EMPTY" icon?
        'iconsPerPage' => 4000, // default 100, how many icons per/page to display
      ),
      'description' => esc_html__('Select icon from library.', 'ajzaa'),
      "dependency" => Array("element" => "ajzaa_switch", "value" => array('ajzaa_icon')),
      "group" => "Icon",
    ),
    array(
      "heading" => esc_html__("Icon Padding", 'ajzaa'),
      "type" => "textfield",
      "param_name" => "box_icon_padding",
      "value" => '0px',
      "group" => "Icon",
    ),
    array(
      "heading" => esc_html__("Icon Margin", 'ajzaa'),
      "type" => "textfield",
      "param_name" => "box_icon_margin",
      "value" => '0',
      "dependency" => Array("element" => "ajzaa_switch", "value" => array('ajzaa_icon')),
      "group" => "Icon",
    ),
    array(
      "type" => "textfield",
      "class" => "",
      "heading" => esc_html__("Icon Font Size", 'ajzaa'),
      "param_name" => "ajzaa_icon_font_size",
      "min" => 14,
      "suffix" => "px",
      "dependency" => Array("element" => "ajzaa_switch", "value" => array('ajzaa_icon')),
      "group" => "Icon",
    ),
    array(
      "heading" => esc_html__("Icon Color", 'ajzaa'),
      "type" => "colorpicker",
      "param_name" => "box_icon_color",
      "value" => '#eee',
      "dependency" => Array("element" => "ajzaa_switch", "value" => array('ajzaa_icon')),
      "group" => "Icon",
    ),

    array(
      "heading" => esc_html__("Icon Border Style", 'ajzaa'),
      "type" => "dropdown",
      "param_name" => "box_icon_border_style",
      "dependency" => Array("element" => "ajzaa_switch", "value" => array('ajzaa_icon')),
      "value" => array(
        'None' => 'none',
        'Solid' => 'solid',
        'dached' => 'dached',
        'dotted' => 'dotted',
        'double' => 'double',
        'groove' => 'groove',
        'ridge' => 'ridge',
        'inset' => 'inset',
        'outset' => 'outset',
      ),
      "group" => "Icon",
    ),
    array(
      "heading" => esc_html__("Icon Background Color", 'ajzaa'),
      "type" => "colorpicker",
      "param_name" => "box_icon_background_color",
      "value" => '#eee',
      "dependency" => Array("element" => "box_icon_border_style", "value" => array('solid', 'dached', 'dotted', 'double', 'groove', 'ridge', 'inset', 'outset')),
      "group" => "Icon",
    ),
    array(
      "heading" => esc_html__("Icon Border Color", 'ajzaa'),
      "type" => "colorpicker",
      "param_name" => "box_icon_border_color",
      "value" => '#eee',
      "dependency" => Array("element" => "box_icon_border_style", "value" => array('solid', 'dached', 'dotted', 'double', 'groove', 'ridge', 'inset', 'outset')),
      "group" => "Icon",
    ),

    array(
      "heading" => esc_html__("Icon Border width", 'ajzaa'),
      "type" => "textfield",
      "param_name" => "box_icon_border_width",
      "value" => '0',
      "dependency" => Array("element" => "box_icon_border_style", "value" => array('solid', 'dached', 'dotted', 'double', 'groove', 'ridge', 'inset', 'outset')),
      "group" => "Icon",
    ),
    array(
      "heading" => esc_html__("Icon Border Radius", 'ajzaa'),
      "type" => "textfield",
      "param_name" => "box_icon_border_radius",
      "value" => '0',
      "dependency" => Array("element" => "box_icon_border_style", "value" => array('solid', 'dached', 'dotted', 'double', 'groove', 'ridge', 'inset', 'outset')),
      "group" => "Icon",
    ),

    //__________________Link_______________________
    array(
      "type" => "textfield",
      "heading" => esc_html__("Link", 'ajzaa'),
      "param_name" => "box_link",
      "value" => "",
      "group" => "Link",
      "dependency" => Array("element" => "box_link_apply", "value" => array('all_box', 'title_box', 'read_more_btn')),
    ),
    array(
      "type" => "textfield",
      "heading" => esc_html__("Read MoreText", 'ajzaa'),
      "param_name" => "box_read_more",
      "value" => "",
      "group" => "Link",
      "dependency" => Array("element" => "box_link_apply", "value" => array('read_more_btn')),
    ),
    array(
      "type" => "textfield",
      "heading" => esc_html__("Read More Class", 'ajzaa'),
      "param_name" => "box_read_more_class",
      "value" => "",
      "group" => "Link",
      "dependency" => Array("element" => "box_link_apply", "value" => array('read_more_btn')),
    ),

    $vc_add_css_animation

  )
));